---
- name: Playbook to create a file/Dir in Host
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Creating a file
    file:
      path: /home/admingsk/demodir
      state: directory
